#!/bin/bash

# check if $1 directory exists
if [ -d "$1" ]; then
    echo "This app already exists"
    exit 1
fi

python manage.py startapp $1

# Create urls.py for the new app
touch $1/urls.py
echo "from django.urls import path" >> $1/urls.py
echo "from django.views.generic import TemplateView" >> $1/urls.py
printf "from .views import *\n\n" >> $1/urls.py
printf "urlpatterns = [\n    path('', TemplateView.as_view(template_name='$1/index.html'), name='$1_index'),\n]" >> $1/urls.py

# Link new app urls.py with the main urls.py of the core application
tail -n 1 "core/urls.py" | wc -c | xargs -I {} truncate "core/urls.py" -s -{}

printf "    path('$1/', include('$1.urls')),\n" >> core/urls.py
printf "]" >> core/urls.py

# Add the new app to the installed apps list
tail -n 1 "core/settings/installed_apps.py" | wc -c | xargs -I {} truncate "core/settings/installed_apps.py" -s -{}

printf "    '$1',\n" >> core/settings/installed_apps.py
printf "]" >> core/settings/installed_apps.py

# Create better testing files for the new app
rm $1/tests.py

mkdir $1/tests
touch $1/tests/__init__.py
touch $1/tests/test.py
touch $1/tests/test_views.py
touch $1/tests/test_models.py

# Add Templates Section
mkdir $1/templates
mkdir $1/templates/$1
touch $1/templates/$1/index.html

echo "{% extends \"base/base.html\" %}" >> $1/templates/$1/index.html 
echo "{% load static %}" >> $1/templates/$1/index.html
printf "\n" >> $1/templates/$1/index.html

echo "{% block title %} Outvite {% endblock %}" >> $1/templates/$1/index.html
printf "\n" >> $1/templates/$1/index.html

echo "<!-- Specific head content applicable to index.html -->" >> $1/templates/$1/index.html
echo "{% block extrahead %}" >> $1/templates/$1/index.html
echo "    <link rel=\"stylesheet\" type=\"text/css\" href=\"{% static '$1/css/$1_style.css' %}\">" >> $1/templates/$1/index.html
echo "    <script src=\"{% static '$1/js/$1_script.js' %}\" defer></script>" >> $1/templates/$1/index.html
echo "{% endblock extrahead %}" >> $1/templates/$1/index.html
printf "\n" >> $1/templates/$1/index.html

echo "<!-- Actual content of index.html -->" >> $1/templates/$1/index.html
echo "{% block content %}" >> $1/templates/$1/index.html
printf "    <p style=\"text-align: center; margin: 5rem;\">$1 app was created</p>\n" >> $1/templates/$1/index.html
echo "{% endblock content %}" >> $1/templates/$1/index.html

# Add Static
mkdir $1/static
mkdir $1/static/$1

# Add Js
mkdir $1/static/$1/js
touch $1/static/$1/js/$1_script.js

printf "/**\n* @author Outvite\n* @copyright Copyright $(date +%Y)\n* @license GPL\n* @version 1.0.0\n* @host Outvite\n* @email outvite@outvite.me\n* @status development\n* @credit 1) This file was auto-generated by a bash script on $(date)\n*/" >> $1/static/$1/js/$1_script.js

# Add CSS
mkdir $1/static/$1/css
touch $1/static/$1/css/$1_style.css

printf "/**\n* @author Outvite\n* @copyright Copyright $(date +%Y)\n* @license GPL\n* @version 1.0.0\n* @host Outvite\n* @email outvite@outvite.me\n* @status development\n* @credit 1) This file was auto-generated by a bash script on $(date)\n*/" >> $1/static/$1/css/$1_style.css
 